# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eb955dc9ee78853cd1586550cc7c837d2f99f164debbf2f1dc9a09d1d748e588a111a3f364ed4d32e929b5cafd792ca9776d12ad9f71c35d7d93011ed9ca4c6

test:
  secret_key_base: 32f4cc7dedacf5f37568b04aa4e5cee1f49d3e3e112ebd920c94cb8157674593d8b44e75388895fd0e18b5cd44718771110bd9ee6bd7b9dab4e1316bbcbdf68a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
